// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: location_info.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const saveLocationInfo = `-- name: SaveLocationInfo :one
INSERT INTO location_info (id, created_at, updated_at, name, web_url, rating, num_reviews)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at, updated_at, name, web_url, rating, num_reviews
`

type SaveLocationInfoParams struct {
	ID         string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Name       string
	WebUrl     sql.NullString
	Rating     sql.NullFloat64
	NumReviews sql.NullInt32
}

func (q *Queries) SaveLocationInfo(ctx context.Context, arg SaveLocationInfoParams) (LocationInfo, error) {
	row := q.db.QueryRowContext(ctx, saveLocationInfo,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.WebUrl,
		arg.Rating,
		arg.NumReviews,
	)
	var i LocationInfo
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.WebUrl,
		&i.Rating,
		&i.NumReviews,
	)
	return i, err
}

const updateLocationInfo = `-- name: UpdateLocationInfo :one
UPDATE location_info
SET updated_at = $4,
    rating = $2,
    num_reviews = $3
WHERE id = $1
RETURNING id, created_at, updated_at, name, web_url, rating, num_reviews
`

type UpdateLocationInfoParams struct {
	ID         string
	Rating     sql.NullFloat64
	NumReviews sql.NullInt32
	UpdatedAt  time.Time
}

func (q *Queries) UpdateLocationInfo(ctx context.Context, arg UpdateLocationInfoParams) (LocationInfo, error) {
	row := q.db.QueryRowContext(ctx, updateLocationInfo,
		arg.ID,
		arg.Rating,
		arg.NumReviews,
		arg.UpdatedAt,
	)
	var i LocationInfo
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.WebUrl,
		&i.Rating,
		&i.NumReviews,
	)
	return i, err
}
