// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: locations.sql

package database

import (
	"context"
)

const getLocationFromId = `-- name: GetLocationFromId :one
SELECT id, name, web_url, rating, num_reviews FROM location_info
WHERE id = $1
`

func (q *Queries) GetLocationFromId(ctx context.Context, id string) (LocationInfo, error) {
	row := q.db.QueryRowContext(ctx, getLocationFromId, id)
	var i LocationInfo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WebUrl,
		&i.Rating,
		&i.NumReviews,
	)
	return i, err
}
