// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Location struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	LocationID string
	Name       string
}

type LocationInfo struct {
	ID         string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Name       string
	WebUrl     sql.NullString
	Rating     sql.NullFloat64
	NumReviews sql.NullInt32
}
