// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Location struct {
	ID         uuid.UUID
	LocationID string
	Name       string
}

type LocationInfo struct {
	ID         string
	Name       string
	WebUrl     sql.NullString
	Rating     sql.NullFloat64
	NumReviews sql.NullInt32
}
