// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Location struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	LocationID string
	Name       string
}

type LocationInfo struct {
	ID         string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Name       string
	WebUrl     sql.NullString
	Rating     sql.NullFloat64
	NumReviews sql.NullInt32
}

type Review struct {
	ID                  uuid.UUID
	CreatedAt           time.Time
	UpdatedAt           time.Time
	TripadvisorReviewID int32
	LocationID          string
	PublishedDate       time.Time
	TripadvisorUrl      sql.NullString
	TripadvisorTitle    sql.NullString
	TripadvisorText     sql.NullString
	Rating              int32
}

type SubReview struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ReviewID      uuid.UUID
	SubratingName string
	Rating        int32
}
