// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reviews.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getReviewCount = `-- name: GetReviewCount :one
SELECT COUNT(*) AS review_count
FROM reviews
WHERE location_id = $1
GROUP BY location_id
`

func (q *Queries) GetReviewCount(ctx context.Context, locationID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getReviewCount, locationID)
	var review_count int64
	err := row.Scan(&review_count)
	return review_count, err
}

const saveReview = `-- name: SaveReview :one
INSERT INTO reviews (id, created_at, updated_at, tripadvisor_review_id, location_id, published_date,
    tripadvisor_url, tripadvisor_title, tripadvisor_text, rating)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, created_at, updated_at, tripadvisor_review_id, location_id, published_date, tripadvisor_url, tripadvisor_title, tripadvisor_text, rating
`

type SaveReviewParams struct {
	ID                  uuid.UUID
	CreatedAt           time.Time
	UpdatedAt           time.Time
	TripadvisorReviewID int32
	LocationID          string
	PublishedDate       time.Time
	TripadvisorUrl      sql.NullString
	TripadvisorTitle    sql.NullString
	TripadvisorText     sql.NullString
	Rating              int32
}

func (q *Queries) SaveReview(ctx context.Context, arg SaveReviewParams) (Review, error) {
	row := q.db.QueryRowContext(ctx, saveReview,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.TripadvisorReviewID,
		arg.LocationID,
		arg.PublishedDate,
		arg.TripadvisorUrl,
		arg.TripadvisorTitle,
		arg.TripadvisorText,
		arg.Rating,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TripadvisorReviewID,
		&i.LocationID,
		&i.PublishedDate,
		&i.TripadvisorUrl,
		&i.TripadvisorTitle,
		&i.TripadvisorText,
		&i.Rating,
	)
	return i, err
}

const saveSubReview = `-- name: SaveSubReview :one
INSERT INTO sub_reviews (id, created_at, updated_at, review_id, subrating_name, rating)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at, updated_at, review_id, subrating_name, rating
`

type SaveSubReviewParams struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ReviewID      uuid.UUID
	SubratingName string
	Rating        int32
}

func (q *Queries) SaveSubReview(ctx context.Context, arg SaveSubReviewParams) (SubReview, error) {
	row := q.db.QueryRowContext(ctx, saveSubReview,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ReviewID,
		arg.SubratingName,
		arg.Rating,
	)
	var i SubReview
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewID,
		&i.SubratingName,
		&i.Rating,
	)
	return i, err
}
